### PR TITLE
Added Tags support for database cluster

### LINKED ISSUE #253: Add tagging support to the digitalocean_database_cluster resource
Hey. I'm unable to tag by database cluster. Is it excepted?

### Terraform Version
```
Terraform v0.12.1
+ provider.aws v2.14.0
+ provider.digitalocean v1.4.0
```
### Affected Resource(s)
- digitalocean_database_cluster
- digitalocean_tag

### Terraform Configuration Files
```hcl
resource "digitalocean_tag" "microservice" {
  name = "backend"
}

resource "digitalocean_database_cluster" "backend-db" {
  name       = "backend-db"
  engine     = "pg"
  version    = "11"
  size       = "db-s-1vcpu-1gb"
  region     = "fra1"
  node_count = 1
  tags = [digitalocean_tag.microservice.id]
}
```

### Debug Output
https://gist.github.com/rozhok/b6e48bf85e6a4fd73005deb0a9ec3e97

### Expected Behavior
Tags should be successfully added to the db cluster.

### Actual Behavior
Tags are not added:
```
Error: Unsupported argument

  on ../config/databases.tf line 12, in resource "digitalocean_database_cluster" "backend-db":
  12:   tags = [digitalocean_tag.microservice.id]

An argument named "tags" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### PR DESCRIPTION
**Pull request by Zyqsempai**
Fixes #253 
Added tags support for database_cluster

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@andrewsomething PTAL

**Comment by andrewsomething** [comment]
Thanks for picking this up @Zyqsempai! The changes look good, but the tests aren't happy:

```
60.07s$ make test
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
# github.com/terraform-providers/terraform-provider-digitalocean/digitalocean
digitalocean/datasource_digitalocean_database_cluster.go:148:20: db.Tags undefined (type godo.Database has no field or method Tags)
digitalocean/resource_digitalocean_database_cluster.go:134:3: unknown field 'Tags' in struct literal of type godo.DatabaseCreateRequest
digitalocean/resource_digitalocean_database_cluster.go:260:24: database.Tags undefined (type *godo.Database has no field or method Tags)
make: *** [test] Error 1
```

This is because we check in dependencies in the `vendor/` directory. You updated the `go.mod` file, but you still need to run `go mod vendor; go mod tidy`, and then commit the changes.

**Comment by Zyqsempai** [comment]
@andrewsomething Done!

**Comment by andrewsomething** [comment]
Merged! Thanks again for your work on this. 🙌

**Pull request merged**
