### PR TITLE
detaching the disks before deleting a droplet

### PR DESCRIPTION
**Pull request by djsly**
fixes: https://github.com/terraform-providers/terraform-provider-digitalocean/issues/19

1) made waitForDropletAttribute private
2) renamed resize_disk to resizeDisk
3) Added a new private helper function: detachVolumeIDOnDroplet

### CODE REVIEW

**Comment by djsly** [comment]
Before this PR
````
make testacc TEST=./digitalocean TESTARGS='-run=TestAccDigitalOceanVolume*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./digitalocean -v -run=TestAccDigitalOceanVolume* -timeout 120m
=== RUN   TestAccDigitalOceanVolume_importBasic
--- PASS: TestAccDigitalOceanVolume_importBasic (11.38s)
=== RUN   TestAccDigitalOceanVolume_Basic
--- PASS: TestAccDigitalOceanVolume_Basic (6.53s)
=== RUN   TestAccDigitalOceanVolume_Droplet
--- FAIL: TestAccDigitalOceanVolume_Droplet (60.18s)
	testing.go:492: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.
		
		Error: Error applying: 1 error(s) occurred:
		
		* digitalocean_volume.foobar (destroy): 1 error(s) occurred:
		
		* digitalocean_volume.foobar: Error deleting volume: DELETE https://api.digitalocean.com/v2/volumes/bb89d1d2-60f0-11e7-a01e-0242ac110c05: 409 A volume that's attached to a Droplet cannot be deleted. Please detach it first before deleting.
		
		State: digitalocean_volume.foobar:
		  ID = bb89d1d2-60f0-11e7-a01e-0242ac110c05
		  description = peace makes plenty
		  droplet_ids.# = 1
		  droplet_ids.2738855229 = 53996792
		  name = volume-qfveuxndub
		  region = nyc1
		  size = 100
FAIL
exit status 1
FAIL	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	78.104s
make: *** [testacc] Error 1
````

After this PR
````
15:43 $ make testacc TEST=./digitalocean TESTARGS='-run=TestAccDigitalOceanVolume*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./digitalocean -v -run=TestAccDigitalOceanVolume* -timeout 120m
=== RUN   TestAccDigitalOceanVolume_importBasic
--- PASS: TestAccDigitalOceanVolume_importBasic (7.84s)
=== RUN   TestAccDigitalOceanVolume_Basic
--- PASS: TestAccDigitalOceanVolume_Basic (6.96s)
=== RUN   TestAccDigitalOceanVolume_Droplet
--- PASS: TestAccDigitalOceanVolume_Droplet (53.80s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	68.618s
````

**Comment by djsly** [comment]
@stack72 let me know if you have comments. This is currently affecting us as we cannot delete our cluster in DigitialOcean anymore. CI pipeline are all red due to the failure un removing the disks.

**Comment by djsly** [comment]
Also, could we add this to the 0.9.X release branch ?

**Comment by stack72** [comment]
Hi @djsly 

Thanks for the work here - this helps us with another set of green acceptance tests :)

```
% make testacc TEST=./digitalocean TESTARGS='-run=TestAccDigitalOceanVolume_Droplet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./digitalocean -v -run=TestAccDigitalOceanVolume_Droplet -timeout 120m
=== RUN   TestAccDigitalOceanVolume_Droplet
--- PASS: TestAccDigitalOceanVolume_Droplet (59.62s)
PASS
ok  	github.com/terraform-providers/terraform-provider-digitalocean/digitalocean	59.634s
```

Paul

**Comment by stack72** [comment]
@djsly, unfortunately, this won't be back ported to the 0.9.x series - this will only be available for the 0.10 release

**Comment by djsly** [comment]
Thanks Paul for the quick merge.  Appreciate.

**Pull request merged**
