### PR TITLE
resource_digitalocean_firewall.go: Add DO Cloud Firewalls (#15124)

### PR DESCRIPTION
**Pull request by keinohguchi**
https://www.digitalocean.com/products/cloud-firewalls/
https://blog.digitalocean.com/cloud-firewalls-secure-droplets-by-default/
https://github.com/digitalocean/godo/commit/4fa9e9d999007b447089056a1c581b5594f0f851

```
air$ go test -v -run TestAccDigitalOceanFirewall
=== RUN   TestAccDigitalOceanFirewall_importBasic
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22)_and_HTTP(TCP/80)
=== RUN   TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22)_and_DNS(UDP/53)
=== RUN   TestAccDigitalOceanFirewall_importBasic/allow_inbound_and_outbound_HTTPS(TCP/443),_inbound_SSH(TCP/22),_and_outbound_DNS(UDP/53)
--- PASS: TestAccDigitalOceanFirewall_importBasic (19.14s)
--- PASS: TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22) (3.89s)
--- PASS: TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22) (4.61s)
--- PASS: TestAccDigitalOceanFirewall_importBasic/only_allow_inbound_SSH(TCP/22)_and_HTTP(TCP/80) (3.48s)
--- PASS: TestAccDigitalOceanFirewall_importBasic/only_allow_outbound_SSH(TCP/22)_and_DNS(UDP/53) (4.05s)
--- PASS: TestAccDigitalOceanFirewall_importBasic/allow_inbound_and_outbound_HTTPS(TCP/443),_inbound_SSH(TCP/22),_and_outbound_DNS(UDP/53) (3.11s)
=== RUN   TestAccDigitalOceanFirewall_Basic
=== RUN   TestAccDigitalOceanFirewall_Basic/only_allow_inbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_Basic/only_allow_outbound_SSH(TCP/22)
=== RUN   TestAccDigitalOceanFirewall_Basic/only_allow_inbound_SSH(TCP/22)_and_HTTP(TCP/80)
=== RUN   TestAccDigitalOceanFirewall_Basic/only_allow_outbound_SSH(TCP/22)_and_DNS(UDP/53)
=== RUN   TestAccDigitalOceanFirewall_Basic/allow_inbound_and_outbound_HTTPS(TCP/443),_inbound_SSH(TCP/22),_and_outbound_DNS(UDP/53)
--- PASS: TestAccDigitalOceanFirewall_Basic (18.77s)
--- PASS: TestAccDigitalOceanFirewall_Basic/only_allow_inbound_SSH(TCP/22) (3.56s)
--- PASS: TestAccDigitalOceanFirewall_Basic/only_allow_outbound_SSH(TCP/22) (3.73s)
--- PASS: TestAccDigitalOceanFirewall_Basic/only_allow_inbound_SSH(TCP/22)_and_HTTP(TCP/80) (3.21s)
--- PASS: TestAccDigitalOceanFirewall_Basic/only_allow_outbound_SSH(TCP/22)_and_DNS(UDP/53) (3.84s)
--- PASS: TestAccDigitalOceanFirewall_Basic/allow_inbound_and_outbound_HTTPS(TCP/443),_inbound_SSH(TCP/22),_and_outbound_DNS(UDP/53) (4.43s)
PASS ok github.com/terraform-providers/terraform-provider-digitalocean/digitalocean 37.920s
air$
```

### CODE REVIEW

**Comment by keinohguchi** [comment]
If something that I miss, let me know, @stack72!  I'm open to any suggestions for improvements!

Thank you for your support, Paul!

Cheers!

**Comment by acejam** [comment]
Patiently waiting for this! 👍

**Comment by stack72** [comment]
Hi @keinohguchi 

I am going to bring this down locally and make a few changes to it. In essence, we tend to use single blocks for Lists

e.g. 

```
outbound_rules = [
                 {
                     protocol              = "tcp"
                     port_range            = "22"
                     destination_addresses = ["192.168.1.0/24", "2002:1001::/48"]
                 },
                 {
                     protocol              = "udp"
                     port_range            = "53"
                     destination_addresses = ["1.2.3.0/24", "2002::/16"]
                 },
                ]
``` breaks our naming convention and therefore, it should be represented as:

```
 outbound_rule {
                     protocol              = "tcp"
                     port_range            = "22"
                     destination_addresses = ["192.168.1.0/24", "2002:1001::/48"]
                 } 

outbound_rule{
                     protocol              = "udp"
                     port_range            = "53"
                     destination_addresses = ["1.2.3.0/24", "2002::/16"]
                 }
```

The multiple blocks follows the DSL style that we use in other resources. The other change I am going to make is to remove the parallelisation from the tests. We manage that in a different way in our CI environment

This will be merged today and i will follow up with the commit sha's to show you the changes I have made

Thanks for the patience here

Paul

**Comment by keinohguchi** [comment]
Sounds good, Paul, and thank you so much for making it happen!

Looking forward to seeing that change!  It's a great way to learn new things! :)

Cheers!

**Comment by stack72** [comment]
Hi @keinohguchi 

This now works as expected :) and formats to our internal way of working

Thanks for all of the work here - the final commit to add this work is [here](https://github.com/terraform-providers/terraform-provider-digitalocean/commit/057591dd7818b1356a070858239769041e24f8c5)

Paul

**Comment by acejam** [comment]
Now that this is merged in, what does one need to do in order to reference this new resource? Wait for a new Terraform release?

**Comment by keinohguchi** [comment]
Thanks @stack72, to make it happen!  Let me pull it and modify github.com/keinohguchi/do-in-action to account for it!

Thank you again for your help, Paul!

Cheers,

**Comment by keinohguchi** [comment]
@acejam, good question!  I believe with the new separate provider style, it should be straight forward to use the new version of the DO provider.  I'll put a way I do once when I modify my [do-in-action](https://github.com/keinohguchi/do-in-action).

Thank you for your interest, @acejam, and it will be super fun to call Cloud Firewalls through terraform!

**Comment by keinohguchi** [comment]
Hi @acejam!

I wrote a simple ansible tasks to set it up for you.  It basically `go get` and `make build` with the latest terraform & DO provider.

https://github.com/keinohguchi/arch-on-air/blob/master/tasks/terraform.yml

Happy firewalling!

**Comment by keinohguchi** [comment]
I've updated [do-in-action](https://github.com/keinohguchi/do-in-action) and all cool with the new terraform!

https://github.com/keinohguchi/do-in-action#test-matrix

Happy Firewalling!

**Comment by stack72** [comment]
Hi @keinohguchi / @acejam 

I'd like to make it perfectly clear that if you are building from Terraform master right now, there is a high chance that you will find an issue. We have not yet released a beta of 0.10 so there will likely be some issues.

We believe we are getting closer to a beta version being available. Only when we hit a full RTM version of 0.10, will this be generally available

Paul

**Comment by keinohguchi** [comment]
Thank you, @stack72, for letting us know!

No problem, and I love bleeding edge!

Thank you for your support, Paul!

**Pull request merged**
